# Generated by Django 4.2.2 on 2023-07-02 15:57

from django.db import migrations
import django.db.models.deletion
import geometry_msgs.msg._pose
import ros2_django.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    ros2_django.fields.RosBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("name", ros2_django.fields.RosCharField(max_length=128)),
                ("description", ros2_django.fields.RosTextField(blank=True)),
                (
                    "webp",
                    ros2_django.fields.RosImageField(
                        blank=True, editable=True, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PoseOnMap",
            fields=[
                (
                    "id",
                    ros2_django.fields.RosBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("name", ros2_django.fields.RosCharField(max_length=128)),
                (
                    "pose",
                    ros2_django.fields.RosMsgField(
                        ros_msg=geometry_msgs.msg._pose.Pose,
                        ros_type="geometry_msgs/Pose",
                    ),
                ),
                (
                    "map",
                    ros2_django.fields.RosForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="example_app.map",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
